# Generated by Django 5.2.7 on 2025-11-04 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GovtJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.TextField(blank=True, null=True)),
                ('job_url', models.URLField(blank=True, max_length=500, null=True, unique=True)),
                ('vacancies', models.CharField(blank=True, max_length=100, null=True)),
                ('deadline', models.CharField(blank=True, max_length=200, null=True)),
                ('posted_date', models.CharField(blank=True, max_length=100, null=True)),
                ('scraped_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Government Job',
                'verbose_name_plural': 'Government Jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='bdgovjob_go_created_7b8bfe_idx'), models.Index(fields=['job_url'], name='bdgovjob_go_job_url_cccdc9_idx')],
            },
        ),
    ]
