# Generated by Django 5.2.7 on 2025-10-31 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_logo_url', models.URLField(blank=True)),
                ('position', models.CharField(max_length=255)),
                ('job_url', models.URLField(blank=True)),
                ('scraped_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_logo_url', models.URLField(blank=True, null=True)),
                ('position', models.CharField(max_length=255)),
                ('job_url', models.URLField()),
                ('scraped_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
