# Generated by Django 5.2.7 on 2025-10-31 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('n8n_integration', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.AlterModelOptions(
            name='hotjob',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='hotjob',
            name='company_logo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hotjob',
            name='company_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hotjob',
            name='job_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hotjob',
            name='position',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hotjob',
            name='scraped_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
